version: '3.1'

services:
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: orp101099
      POSTGRES_DB: gubee
    ports:
      - "5432:5432"
    volumes:
      - ./core/src/main/resources/db/schema/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    networks:
      - gubee_network

  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379"
    networks:
      - gubee_network

networks:
  gubee_network:
