---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-commit: 3400bd18eefe973505a051e2af2223bcf03e3abd
    fabric8.io/git-branch: master
    fabric8.io/git-url: https://github.com/dudupuci/test-for-devs-gubee.git
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/teste-dev-gubee-main/application
    fabric8.io/scm-tag: HEAD
  labels:
    app: application
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: gubee
  name: application
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: application
    provider: fabric8
    group: gubee
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 3400bd18eefe973505a051e2af2223bcf03e3abd
        fabric8.io/git-branch: master
        fabric8.io/scm-tag: HEAD
        fabric8.io/git-url: https://github.com/dudupuci/test-for-devs-gubee.git
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/teste-dev-gubee-main/application
      labels:
        app: application
        provider: fabric8
        version: 1.0.0-SNAPSHOT
        group: gubee
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gubee/teste-pleno-gubee:latest
        imagePullPolicy: IfNotPresent
        name: teste-pleno-gubee-api
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
